### ISSUE TITLE
Přejmenujte workspace v Toggl Track

### ISSUE THREAD

**Issue by e-m-s** [vlshk999/SpaceLight#4]
Pojmenujte workspace v Toggl Track podle vzoru: "Název projektu - Příjmení 1, Příjmení 2".

Nastavte viditelnost pro vyučujícího - buď nastavte vyučujícího jako admina Workspace, nebo jako manažera projektu.

**Comment by MatejBlaha** [comment]
Toggl dola

**Comment by MatejBlaha** [comment]
Toggl doladěn
